title: "BEIJING ZI YUE HAI SHI CULTURAL MEDIA TECHNOLOGY CO., LTD"
email: "727755310@qq.com"
baseurl: ""
url: "https://www.ziyuehaishi.com"

collections:
  movies:
    output: true
    permalink: /movies/:name/

markdown: kramdown
theme: minima

defaults:
  - scope:
      path: ""
      type: "movies"
    values:
      layout: "movie"
